[project]
name = "layup-api"
version = "0.1.0"
description = "Layup backend HTTP REST API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic-extra-types>=2.10.3",
    "python-ulid[pydantic]>=3.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]
